POST http://localhost:7000/api/Blocks
Content-Type: application/json
Accept: application/json

{
  "blockDurability": "1",
  "blockname" : "Dirtblock",
  "name" : "Dirt",
  "size" : 1
  }
###
POST http://localhost:7000/api/Blocks
Content-Type: application/json
Accept: application/json

{
  "blockDurability": "5",
  "blockname" : "Stoneblock",
  "name" : "Stone",
  "size" : 3
}
###

GET http://localhost:7000/api/Blocks/
###
GET http://localhost:7000/api/Blocks/1