
GET http://localhost:7000/api/user/
###
POST http://localhost:7000/api/user/
Content-Type: application/json
Accept: application/json

{
  "firstname": "Hans",
  "name" : "Hinterseer",
  "username" : "Hirni09"
}